import { Geist, Geist_Mono, Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
export const poppins = Poppins({
 variable: "--font-poppins",
  subsets: ["latin"], 
   weight: ["400", "500", "600", "700"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col ${poppins.className}`}>
        <Navbar></Navbar>
        {children}
          <Footer></Footer>
           <ToastContainer position="top-center"
           autoClose={2000}
           
           />
        </body>
        
    </html>
  );
}
